# CircleCI configuration file

version: 2.1
executors:
  docker-node:
    docker:
      - image: cimg/node:lts
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/gitnlsn/spotify-suggestions/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
  docker-python:
    docker:
      - image: cimg/python:3.9.6

jobs:
  tests:
    executor: docker-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run Tests
          command: npx jest --coverage
      - run:
          name: Download executable
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run:
          name: Make executable
          command: chmod +x codecov
      - run:
          name: Run codecov
          command: ./codecov
  build:
    environment:
      CI: ""
    executor: docker-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build
          command: npx react-scripts build
  security:
    executor: docker-python
    steps:
      - checkout
      - run:
          name: Install njsscan
          command: pip install --upgrade njsscan
      - run:
          name: njsscan check
          command: njsscan .

workflows:
  basic-workflow:
    jobs:
      - tests
      - build
      - security
