# CircleCI configuration file

version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/gitnlsn/spotify-suggestions/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  tests:
    environment:
      REACT_APP_SPOTIFY_CLIENT_ID: $REACT_APP_SPOTIFY_CLIENT_ID
      REACT_APP_SPOTIFY_CLIENT_SECRET: $REACT_APP_SPOTIFY_CLIENT_SECRET
    executor: my-custom-executor
    steps:
      - checkout
      - run: yarn
      - run: |
          npx jest --coverage

workflows:
  my-custom-workflow:
    jobs:
      - tests